### ISSUE TITLE
Netlify?

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2-e2e-tests#46]
For a quick reproduction I today tried to deploy something to Netlify. I thought I could look into this repository to get an idea, but that was not really true.

Some questions:

- What is the difference between netlify, netlify-ci-build and netlify-zishi? Should this be documented? What is the state of those? All good to use? All current and in use?
- READMEs
   - https://github.com/prisma/prisma2-e2e-tests/tree/master/platforms/netlify-zishi#deployment tells me to use `linux-glibc-libssl1.0.1` in `platforms` (?) and set `output` but does not do that in `schema.prisma` and also not in the script
   - https://github.com/prisma/prisma2-e2e-tests/tree/master/platforms/netlify seems to have the same README in general, but at least `output` is used in the project this time.
   - Wasn't `platform` renamed to `binaryTargets`?
- netlify-zishi
	- ZISHI = ZISI?
	- `git@github.com:divyenduz/netlify-zishi.git`?
	- Where does https://github.com/divyenduz/netlify-zishi actually do the zipping and shipping?

**Comment by steebchen** [comment]
@divyenduz It would be great if you could provide more details in this issue why there are different Netlify projects and if there's anything we can recommend for our users.

**Comment by divyenduz** [comment]
@steebchen There are different netlify projects here because there are different ways to deploy to netlify. Users can deploy with any of the methods and we need to test all of them. 

Netlify beta uses are newer version of ZISI and just works. Currently, netlify uses an older version of ZISI and needs additional steps for binary bundling. 

The folder `netlify-zisi` is an experiment (failed so far) to get a newer version of ZISI on current netlify with an env var.

**Comment by janpio** [comment]
Please remove the failed experiment from the repo and put it in a Draft PR instead.

The remaining projects/setups needs clear READMEs that explain the differences, and probably also crosslink to point out the alternatives.

**Comment by divyenduz** [comment]
I guess all the things in this issue are not addressed.
